// Copyright 2012 Google Inc. All Rights Reserved.

package com.google.vr.cardboard.paperscope.demo.photosphere.lightcycle.util;

import android.graphics.BitmapFactory;
import android.util.Log;
import com.adobe.xmp.XMPException;
import com.adobe.xmp.XMPMeta;
import com.google.vr.cardboard.paperscope.demo.photosphere.lightcycle.xmp.PanoConstants;
import com.google.vr.cardboard.paperscope.demo.photosphere.lightcycle.xmp.XmpUtil;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.InputStream;
import java.util.Calendar;
import org.jspecify.annotations.Nullable;

/**
 * Reads the meta data from a panorama file.
 *
 * TODO(bwuest): This should not be forked from lightcycle, but rather shared as a library, can
 * be included through LightCycleCoreLib.
 * @author haeberling@google.com (Sascha Haeberling)
 */
public class PanoMetadata {
  private static final String TAG = "PanoMetadata";

  /** Width of the image in pixels. */
  public final int imageWidth;
  /** Height of the image in pixels. */
  public final int imageHeight;

  /** Time the first photo of the pano series was taken. */
  public final Calendar firstPhotoTime;
  /** Time the last photo of the pano series was taken. */
  public final Calendar lastPhotoTime;
  /** The number of photos to produce the panorama. */
  public final int sourcePhotosCount;
  /** The projection type needed to display the panorama correctly. */
  public final String projectionType;
  /** Whether a panorama viewer should be used. */
  public final boolean usePanoViewer;

  /** The width of the cropped area in pixels. */
  public final int croppedAreaWidth;
  /** The height of the cropped area in pixels. */
  public final int croppedAreaHeight;
  /** The width of the original full 360x180 degree pano in pixels. */
  public final int fullPanoWidth;
  /** The height of the original full 360x180 degree pano in pixels. */
  public final int fullPanoHeight;
  /**
   * The offset of the cropped area from the left edge of the fullsize pano in
   * pixels.
   */
  public final int croppedAreaLeft;
  /**
   * The offset of the cropped area from the top edge of the fullsize pano in
   * pixels.
   */
  public final int croppedAreaTop;

  /**
   * Compass heading, measured in degrees, for the center of the image. Value must
   * be >= 0 and < 360.
   * <p>
   * The order in which heading, pitch and roll are applied is important. See
   * https://developers.google.com/photo-sphere/metadata/ for details.
   */
  public float poseHeadingDegrees;

  /**
   * Pitch, measured in degrees, for the center of the image. Value must be >=
   * -90 and <= 90.
   * <p>
   * The order in which heading, pitch and roll are applied is important. See
   * https://developers.google.com/photo-sphere/metadata/ for details.
   */
  public final float posePitchDegrees;

  /**
   * Roll, measured in degrees, of the image where level with the horizon is 0.
   * Value must be > -180 and <= 180.
   * <p>
   * The order in which heading, pitch and roll are applied is important. See
   * https://developers.google.com/photo-sphere/metadata/ for details.
   */
  public final float poseRollDegrees;

  /**
   * Whether the meta-data was synthetically generated by a 2:1 file without
   * meta data.
   */
  public final boolean synthetic;

  /**
   * Depthmap associated to the panorama. This field is optional and can be null.
   */
  public DepthMap depthMap;

  /**
   * Creating an instance will cause the specified file's meta data to be
   * parsed.
   */
  private PanoMetadata(int imageWidth, int imageHeight, Calendar firstPhotoTime,
      Calendar lastPhotoTime, int sourcePhotosCount, String projectionType,
      boolean usePanoViewer, int croppedAreaWidth, int croppedAreaHeight,
      int fullPanoWidth, int fullPanoHeight, int croppedAreaLeft,
      int croppedAreaTop, float poseHeadingDegrees, float posePitchDegrees,
      float poseRollDegrees, boolean synthetic) {
    this.imageWidth = imageWidth;
    this.imageHeight = imageHeight;
    this.firstPhotoTime = firstPhotoTime;
    this.lastPhotoTime = lastPhotoTime;
    this.sourcePhotosCount = sourcePhotosCount;
    this.projectionType = projectionType;
    this.usePanoViewer = usePanoViewer;
    this.croppedAreaWidth = croppedAreaWidth;
    this.croppedAreaHeight = croppedAreaHeight;
    this.fullPanoWidth = fullPanoWidth;
    this.fullPanoHeight = fullPanoHeight;
    this.croppedAreaLeft = croppedAreaLeft;
    this.croppedAreaTop = croppedAreaTop;
    this.poseHeadingDegrees = poseHeadingDegrees;
    this.posePitchDegrees = posePitchDegrees;
    this.poseRollDegrees = poseRollDegrees;
    this.synthetic = synthetic;
  }

  /**
   * Create a new instance of PanoMetadata. This is used for example where the source
   * will be a panorama served from cityblock and we have not yet loaded any tile images
   * for it. The width and height should be the size at the desired zoom level that is
   * being fetched, not necessarily the full size of the available image.
   *
   * If this constructor is used directly no checks on aspect ratio etc. are performed
   * and these must be done by the caller.
   *
   * @param imageWidth The width of the panorama at the desired zoom level in pixels
   * @param imageHeight The height of the panorama at the desired zoom level in pixels
   */
  public PanoMetadata(int imageWidth, int imageHeight) {
    this.imageWidth = imageWidth;
    this.imageHeight = imageHeight;
    firstPhotoTime = Calendar.getInstance();
    lastPhotoTime = Calendar.getInstance();
    sourcePhotosCount = -1;
    projectionType = PanoConstants.PROPERTY_VALUE_EQUIRECTANGULAR;
    usePanoViewer = true;
    croppedAreaWidth = imageWidth;
    croppedAreaHeight = imageHeight;
    croppedAreaLeft = 0;
    croppedAreaTop = 0;
    fullPanoWidth = imageWidth;
    fullPanoHeight = imageHeight;
    poseHeadingDegrees = 0;
    posePitchDegrees = 0;
    poseRollDegrees = 0;
    synthetic = true;
  }

  /**
   * Sets the depthmap associated to the panorama.
   */
  public void setDepthMap(DepthMap depthMap) {
    this.depthMap = depthMap;
  }

  /**
   * Sets pose heading offset associated to the panorama.
   */
  public void setPoseHeadingDegrees(float poseHeadingDegrees) {
    this.poseHeadingDegrees = poseHeadingDegrees;
  }

  /**
   * Parses the pano-specific meta data from the given file and returns an
   * instance of {@link PanoMetadata} containing the parsed values.
   *
   * @param filename the name of the file to extract the XMP meta data from.
   * @return The meta data extracted from the file or null, of no XMP meta data
   *         was found, it failed to parse or is invalid.
   */
  public static PanoMetadata parse(final String filename) {
    return parse(
        new InputStreamFactory() {

          @Override
          public @Nullable InputStream create() {
            try {
              return new FileInputStream(filename);
            } catch (FileNotFoundException e) {
              Log.e(TAG, "Could not read file: " + filename, e);
              return null;
            }
          }
        });
  }

  /** See {@link #parse(String)}, but use an {@link InputStream} instead. */
  public static @Nullable PanoMetadata parse(InputStreamFactory isf) {
    InputStream is = isf.create();
    if (is == null) {
      return null;
    }

    Calendar firstPhotoTime = null;
    Calendar lastPhotoTime = null;
    int sourcePhotosCount = 0;
    String projectionType = null;
    boolean usePanoViewer = false;
    int croppedAreaWidth = 0;
    int croppedAreaHeight = 0;
    int fullPanoWidth = 0;
    int fullPanoHeight = 0;
    int croppedAreaLeft = 0;
    int croppedAreaTop = 0;
    float poseHeadingDegrees = 0;
    float posePitchDegrees = 0;
    float poseRollDegrees = 0;
    boolean synthetic = false;

    boolean validMetaData = false;
    XMPMeta xmp = XmpUtil.extractXmpMeta(is);

    if (xmp != null) {
      try {
        firstPhotoTime = getDate(xmp, PanoConstants.FIRST_PHOTO_DATE);
        lastPhotoTime = getDate(xmp, PanoConstants.LAST_PHOTO_DATE);
        sourcePhotosCount = getInt(xmp, PanoConstants.SOURCE_PHOTOS_COUNT);
        projectionType = getString(xmp, PanoConstants.PROPERTY_PROJECTION_TYPE);
        usePanoViewer =
            getBoolean(xmp, PanoConstants.PROPERTY_USE_PANORAMA_VIEWER);
        croppedAreaWidth =
            getInt(xmp, PanoConstants.CROPPED_AREA_IMAGE_WIDTH_PIXELS);
        croppedAreaHeight =
            getInt(xmp, PanoConstants.CROPPED_AREA_IMAGE_HEIGHT_PIXELS);
        fullPanoWidth =
            getInt(xmp, PanoConstants.CROPPED_AREA_FULL_PANO_WIDTH_PIXELS);
        fullPanoHeight =
            getInt(xmp, PanoConstants.CROPPED_AREA_FULL_PANO_HEIGHT_PIXELS);
        croppedAreaLeft = getInt(xmp, PanoConstants.CROPPED_AREA_LEFT);
        croppedAreaTop = getInt(xmp, PanoConstants.CROPPED_AREA_TOP);
        poseHeadingDegrees = (float) getDouble(xmp, PanoConstants.POSE_HEADING_DEGREES);
        posePitchDegrees = (float) getDouble(xmp, PanoConstants.POSE_PITCH_DEGREES);
        poseRollDegrees = (float) getDouble(xmp, PanoConstants.POSE_ROLL_DEGREES);
        synthetic = false;

        validMetaData = croppedAreaWidth > 0 && croppedAreaHeight > 0
            && fullPanoWidth > 0 && fullPanoHeight > 0;
      } catch (XMPException ex) {
        // Use defaults if XMP parsing fails.
      }
    }

    // Get the actual image width and height.
    BitmapFactory.Options options = new BitmapFactory.Options();
    options.inJustDecodeBounds = true;
    is = isf.create();
    try {
      BitmapFactory.decodeStream(is, null, options);
    } finally {
      try {
        if (is != null) {
          is.close();
        }
      } catch (IOException e) {
        // ignore
      }
    }
    int imageWidth = options.outWidth;
    int imageHeight = options.outHeight;
    boolean twoToOneRatio = 2 * imageHeight == imageWidth;
    boolean fallback = false;

    // If the metadata could not be parsed correctly, but the image has a 2:1
    // ration, set defaults suggesting it's a 360x180.
    if (!validMetaData) {
      if (twoToOneRatio) {
        // Could not parse meta data for file. Filling in 360 defaults.
        fallback = true;
      } else {
        // Image has no metadata and no 2:1 aspect ratio. Not a pano!
        return null;
      }
    }

    // Sanity checks: Make sure the given and actual aspect ratios are roughly
    // the same.
    double imageAspectRatio = imageWidth / (double) imageHeight;
    double croppedMetaRatio = croppedAreaWidth / (double) croppedAreaHeight;

    if (!fallback && !isNear(imageAspectRatio, croppedMetaRatio, 0.05)) {
      Log.w(TAG,
          "Pano metadata does not match file dimensions. Image aspect ratio: "
          + imageAspectRatio + ". Metadata aspect ratio: " + croppedMetaRatio);
      return null;
    }

    // Sanity check: Make sure the full pano aspect ratio is roughly 2:1.
    if (!fallback && !isNear(fullPanoWidth / (double) fullPanoHeight, 2, 0.1)) {
      Log.w(TAG, "Pano metadata invalid: Full pano dimension not 2:1.");
      return null;
    }

    if (fallback) {
      // Initializes the metadata for a 2:1 360 degree pano at the specified dimensions
      return new PanoMetadata(imageWidth, imageHeight);
    } else {
      // Initializes the metadata with the values read from XMP.
      return new PanoMetadata(imageWidth, imageHeight, firstPhotoTime,
          lastPhotoTime, sourcePhotosCount, projectionType, usePanoViewer,
          croppedAreaWidth, croppedAreaHeight, fullPanoWidth, fullPanoHeight,
          croppedAreaLeft, croppedAreaTop, poseHeadingDegrees, posePitchDegrees, poseRollDegrees,
          synthetic);
    }
  }

  public boolean isScaled() {
    return this.imageWidth != this.croppedAreaWidth
        || this.imageHeight != this.croppedAreaHeight;
  }

  private static double getDouble(XMPMeta xmp, String key) throws XMPException {
    if (xmp.doesPropertyExist(PanoConstants.GOOGLE_PANO_NAMESPACE, key)) {
      return xmp.getPropertyDouble(PanoConstants.GOOGLE_PANO_NAMESPACE, key);
    } else {
      return 0;
    }
  }

  private static int getInt(XMPMeta xmp, String key) throws XMPException {
    if (xmp.doesPropertyExist(PanoConstants.GOOGLE_PANO_NAMESPACE, key)) {
      return xmp.getPropertyInteger(PanoConstants.GOOGLE_PANO_NAMESPACE, key);
    } else {
      return 0;
    }
  }

  private static @Nullable String getString(XMPMeta xmp, String key) throws XMPException {
    if (xmp.doesPropertyExist(PanoConstants.GOOGLE_PANO_NAMESPACE, key)) {
      return xmp.getPropertyString(PanoConstants.GOOGLE_PANO_NAMESPACE, key);
    } else {
      return null;
    }
  }

  private static boolean getBoolean(XMPMeta xmp, String key)
      throws XMPException {
    if (xmp.doesPropertyExist(PanoConstants.GOOGLE_PANO_NAMESPACE, key)) {
      return xmp.getPropertyBoolean(PanoConstants.GOOGLE_PANO_NAMESPACE, key);
    } else {
      return false;
    }
  }

  private static @Nullable Calendar getDate(XMPMeta xmp, String key) throws XMPException {
    if (xmp.doesPropertyExist(PanoConstants.GOOGLE_PANO_NAMESPACE, key)) {
      return xmp.getPropertyCalendar(PanoConstants.GOOGLE_PANO_NAMESPACE, key);
    } else {
      return null;
    }
  }

  private static boolean isNear(double first, double second, double tolerance) {
    return Math.abs(first - second) < tolerance;
  }

}
