// Used by the code generated by vr/apps/common/tools/genstrings.py.

#ifndef PAPERSCOPE_LAUNCHER_COMMON_STRINGS_LOCALIZED_STRINGS_H_
#define PAPERSCOPE_LAUNCHER_COMMON_STRINGS_LOCALIZED_STRINGS_H_

#include <string>
#include <vector>
#include <unordered_map>
#include <string_view>

namespace cardboard_demo {
typedef std::unordered_map<std::string, std::string> LocaleEntry;
typedef std::unordered_map<std::string, LocaleEntry> LocaleMap;

// Returns the locale strings to try to try for a given locale in order of best
// choice to worst.
// This should be used for retrieving LocaleEntrys from a LocaleMap which is
// autogenerated by //vr/apps/common/tools/localization/genstrings.py.
// "en" is required in any LocaleMap and will thus always be included at the
// end of the vector as a last resort.
std::vector<std::string> GetProbableLocalesInOrder(std::string locale);

// Returns localized string for |key| in the |entry| if it exists, otherwise
// returns nullptr.
const char* GetLocalizedStringFromMap(std::string_view key,
                                      const LocaleEntry& entry);
}  // namespace cardboard_demo


#endif  // PAPERSCOPE_LAUNCHER_COMMON_STRINGS_LOCALIZED_STRINGS_H_
